---
- name: Run ldconfig
  ansible.builtin.command: ldconfig
  changed_when: false

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart llama-server
  ansible.builtin.systemd:
    name: llama-server
    state: restarted
